# Generated by Django 5.0.4 on 2024-07-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='First name', max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Last name', max_length=50, verbose_name='Last name')),
                ('birth', models.DateField(verbose_name='Date of birth')),
            ],
        ),
    ]
