# Generated by Django 5.0.4 on 2024-07-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0002_venue_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Band Name', max_length=20)),
                ('members', models.ManyToManyField(to='bands.musician', verbose_name='Members')),
            ],
        ),
    ]
