# Generated by Django 5.0.4 on 2024-07-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0003_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='BandGroup',
        ),
    ]
