# Generated by Django 5.0.4 on 2024-07-05 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0004_rename_group_bandgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandgroup',
            name='name',
            field=models.CharField(default='Band Group', max_length=20),
        ),
    ]
