# Generated by Django 5.0.4 on 2024-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0006_room_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='style',
            field=models.CharField(default='RELA', help_text='Main style of music', max_length=4, verbose_name='Style of music'),
        ),
    ]
