# Generated by Django 5.0.4 on 2024-07-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0007_musician_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='style',
            field=models.CharField(choices=[('ROCK', 'Rock and roll'), ('RELA', 'Relaxing'), ('LIVE', 'Lively')], default='RELA', help_text='Main style of music', max_length=4, verbose_name='Style of music'),
        ),
    ]
