# Generated by Django 5.0.4 on 2024-07-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0008_alter_musician_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandgroup',
            name='name',
            field=models.CharField(default='Band Group', max_length=20, verbose_name='Band group'),
        ),
    ]
