# Generated by Django 5.0.4 on 2024-07-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0011_venue_description_venue_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, help_text='Max length 300 characters', max_length=300, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(help_text='Name of venue, max characters 20', max_length=20, verbose_name='Venue'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='picture',
            field=models.ImageField(blank=True, help_text='Uplaod a picture of your venue,             in JPG or PNG format only.', null=True, upload_to='', verbose_name='Picture'),
        ),
    ]
