# Generated by Django 5.0.4 on 2024-07-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0012_alter_venue_description_alter_venue_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='description',
            field=models.TextField(default='Practice rooms and performance venues', help_text='Max length 300 characters', max_length=300, verbose_name='Description'),
        ),
    ]
