# Generated by Django 5.0.4 on 2024-07-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0013_alter_venue_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(help_text='Name of venue, max characters 20', max_length=100, verbose_name='Venue'),
        ),
    ]
