# Generated by Django 5.0.4 on 2024-07-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0014_alter_venue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='picture',
            field=models.ImageField(blank=True, help_text='Uplaod a picture of your venue,             in JPG or PNG format only. Not more than 500KB', max_length=500000, null=True, upload_to='', verbose_name='Picture'),
        ),
    ]
