# Generated by Django 5.0.4 on 2024-07-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0015_alter_venue_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='musician',
            name='description',
            field=models.TextField(blank=True, help_text='Description of your profile', max_length=300, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='musician',
            name='picture',
            field=models.ImageField(blank=True, help_text='Photo in JPG and PNG format only. Not more than 500KB.', max_length=500000, null=True, upload_to='', verbose_name='Your profile picture'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='birth',
            field=models.DateField(blank=True, help_text='Data of birth', verbose_name='Date of birth'),
        ),
    ]
