# Generated by Django 5.0.4 on 2024-07-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0016_musician_description_musician_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='birth',
            field=models.DateField(blank=True, error_messages='Enter your date of birth', help_text='Data of birth', verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='description',
            field=models.TextField(blank=True, error_messages='Enter a description', help_text='Description of your profile', max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(error_messages='Enter your first name', help_text='First name', max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(error_messages='Enter your last name', help_text='Last name', max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='picture',
            field=models.ImageField(blank=True, error_messages='Upload a picture', help_text='Photo in JPG and PNG format only. Not more than 500KB.', max_length=500000, null=True, upload_to='', verbose_name='Your profile picture'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='style',
            field=models.CharField(choices=[('ROCK', 'Rock and roll'), ('RELA', 'Relaxing'), ('LIVE', 'Lively')], default='RELA', error_messages='Choose your style of music', help_text='Main style of music', max_length=4, verbose_name='Style of music'),
        ),
    ]
