# Generated by Django 5.0.4 on 2024-07-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bands', '0017_alter_musician_birth_alter_musician_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bandgroup',
            name='members',
            field=models.ManyToManyField(blank=True, to='bands.musician', verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='birth',
            field=models.DateField(blank=True, error_messages='Enter your date of birth', verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='description',
            field=models.TextField(blank=True, error_messages='Enter a description', max_length=300, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='first_name',
            field=models.CharField(error_messages='Enter your first name', max_length=50, verbose_name='First name'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='last_name',
            field=models.CharField(error_messages='Enter your last name', max_length=50, verbose_name='Last name'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='style',
            field=models.CharField(choices=[('ROCK', 'Rock and roll'), ('RELA', 'Relaxing'), ('LIVE', 'Lively')], default='RELA', error_messages='Choose your style of music', max_length=4, verbose_name='Style of music'),
        ),
    ]
