# Generated by Django 5.0.4 on 2024-07-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seekingad',
            name='ads',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='seekingad',
            name='id',
            field=models.SmallAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seekingad',
            name='seeking',
            field=models.CharField(choices=[('M', 'MUSICIAN'), ('B', 'BAND')], max_length=1),
        ),
    ]
