# Generated by Django 5.0.4 on 2024-07-15 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_seekingad_ads_alter_seekingad_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seekingad',
            options={'ordering': ['-create_date']},
        ),
    ]
